export const SEO_KEYWORDS = [
  "Cele One",
  "Cèlè One",
  "CeleOne",
  "Cele One app",
  "CeleOne app",
  "Celeone TV",
  "Cele One TV",
  "Celestial Church of Christ",
  "Celestial Church",
  "CCC",
  "CCC Worldwide",
  "Celestial Church of Christ worldwide",
  "Celestial Church community",
  "Celestial Christian community",
  "Celestial Church of Christ app",
  "Celestial Church app",
  "CCC app",
  "CCC mobile app",
  "Celestial Church social network",
  "Celestial Church social media",
  "Christian community app",
  "Celestial Church community platform",
  "Celestial Church news",
  "CCC news",
  "Celestial Church updates",
  "CCC official information",
  "Celestial Church reforms",
  "Celestial Church announcements",
  "Celestial Church decisions",
  "Celestial Church hymns",
  "CCC hymns",
  "Celestial hymns",
  "Celestial Church hymn book",
  "CCC hymn book",
  "Celestial Church songs",
  "CCC songs",
  "Celestial Church worship songs",
  "Celestial Church weekly theme",
  "CCC weekly theme",
  "theme of the week Celestial Church",
  "Celestial Church Bible lesson",
  "CCC Bible lesson",
  "CCC Bible readings",
  "Celestial Church Bible readings",
  "Celestial Church spiritual program",
  "CCC spiritual program",
  "Celestial Church weekly program",
  "Celestial Church Sunday service",
  "CCC Sunday service",
  "Celestial Church Wednesday service",
  "CCC Wednesday service",
  "Celestial Church Friday service",
  "CCC Friday service",
  "Celestial Church worship program",
  "Celestial Church parish",
  "CCC parish",
  "Celestial Church parish near me",
  "CCC parish near me",
  "find Celestial Church near me",
  "find CCC parish",
  "Celestial Church map",
  "CCC parish map",
  "Celestial Church locations",
  "Celestial Church parishes worldwide",
  "Celestial Church parishes Benin",
  "Celestial Church parishes Nigeria",
  "Celestial Church live",
  "CCC live",
  "Celestial Church live TV",
  "CCC live TV",
  "Celestial Church online",
  "Celestial Church livestream",
  "Christian TV live",
  "Celestial Church radio",
  "CCC radio",
  "Celestial Church documents",
  "CCC official documents",
  "Celestial Church constitution",
  "CCC constitution",
  "Celestial Church doctrine",
  "CCC doctrine",
  "Celestial Church order of service",
  "CCC order of worship",
  "Celestial Church harvest",
  "CCC harvest",
  "Celestial Church Christmas",
  "Celestial Church Easter",
  "Celestial Church Pentecost",
  "Celestial Church crossover service",
  "Samuel Bilehou Joseph Oshoffa",
  "Samuel B. J. Oshoffa",
  "SBJ Oshoffa",
  "Pastor Oshoffa",
  "Celestial Church founder",
  "founder of Celestial Church of Christ",
  "application Cèlè One",
  "application CeleOne",
  "plateforme Cèlè One",
  "Église du Christianisme Céleste",
  "Eglise du Christianisme Celeste",
  "Église Céleste",
  "Eglise Celeste",
  "Christianisme Céleste",
  "communauté céleste",
  "chrétiens célestes",
  "application Église du Christianisme Céleste",
  "application ECC",
  "application chrétienne céleste",
  "réseau social ECC",
  "plateforme sociale ECC",
  "plateforme Église du Christianisme Céleste",
  "actualités ECC",
  "actualité Église du Christianisme Céleste",
  "informations ECC",
  "annonces ECC",
  "décisions ECC",
  "réformes ECC",
  "cantiques célestes",
  "cantiques ECC",
  "recueil de cantiques célestes",
  "recueil cantiques ECC",
  "cantiques Église du Christianisme Céleste",
  "chants célestes",
  "chants ECC",
  "thème de la semaine ECC",
  "thème hebdomadaire ECC",
  "thème de la semaine Église Céleste",
  "programme spirituel ECC",
  "programme spirituel Église du Christianisme Céleste",
  "lectures bibliques ECC",
  "textes bibliques ECC",
  "culte du mercredi ECC",
  "culte du vendredi ECC",
  "culte du dimanche ECC",
  "culte dominical ECC",
  "programme des cultes ECC",
  "horaires des cultes ECC",
  "paroisse ECC",
  "paroisse céleste",
  "paroisse ECC près de moi",
  "Église Céleste près de moi",
  "trouver une paroisse ECC",
  "localiser une paroisse ECC",
  "géolocalisation paroisses ECC",
  "carte des paroisses ECC",
  "paroisses célestes au Bénin",
  "paroisses ECC au Bénin",
  "paroisses ECC en Côte d'Ivoire",
  "paroisses ECC en France",
  "ECC en direct",
  "Église Céleste en direct",
  "Culte ECC en direct",
  "TV ECC",
  "Web TV ECC",
  "Radio ECC",
  "streaming Église Céleste",
  "documents officiels ECC",
  "documents Église du Christianisme Céleste",
  "constitution ECC",
  "constitution Église Céleste",
  "doctrine ECC",
  "ordre du culte ECC",
  "règlements ECC",
  "moisson ECC",
  "fête des moissons ECC",
  "Noël ECC",
  "Pâques ECC",
  "Pentecôte ECC",
  "crossover ECC",
  "Samuel Biléhou Joseph Oshoffa",
  "Samuel B.J. Oshoffa",
  "Papa Oshoffa",
  "fondateur Église du Christianisme Céleste",
  "Ijo Mimo ti Kristi lati orun wa",
  "Ijo Mimo ti Kristi lati Orun Wa",
  "Celestial Church Yoruba",
  "CCC Yoruba",
  "Celestial Church of Christ Yoruba",
  "Cele One Yoruba",
  "CeleOne Yoruba",
  "CCC app Yoruba",
  "Celestial Church app Yoruba",
  "CCC Yoruba hymns",
  "Celestial Church Yoruba hymns",
  "CCC Yoruba songs",
  "CCC Yoruba weekly theme",
  "CCC Yoruba Bible lessons",
  "CCC Yoruba spiritual program",
  "CCC Yoruba parish",
  "CCC Yoruba parishes",
  "Celestial Church Yoruba parish",
  "CCC Nigeria parishes",
  "CCC Fon",
  "ECC Fon",
  "Cele One Fon",
  "Cèlè One Fon",
  "Église du Christianisme Céleste Fon",
  "cantiques célestes Fon",
  "cantiques ECC Fon",
  "thème de la semaine Fon",
  "programme spirituel ECC Fon",
  "lectures bibliques ECC Fon",
  "CCC Goun",
  "CCC Gungbe",
  "ECC Goun",
  "ECC Gungbe",
  "Cele One Goun",
  "Cele One Gungbe",
  "cantiques Goun",
  "cantiques Gungbe",
  "thème ECC Goun",
  "programme spirituel Gungbe",
  "Celestial Church of Christ en español",
  "Iglesia del Cristianismo Celestial",
  "Iglesia Celestial",
  "CCC español",
  "Cele One español",
  "aplicación Cele One",
  "aplicación Celestial Church",
  "aplicación CCC",
  "himnos Celestiales",
  "himnos CCC",
  "canciones Celestial Church",
  "tema semanal Celestial Church",
  "tema de la semana CCC",
  "programa espiritual CCC",
  "lecturas bíblicas CCC",
  "parroquia Celestial Church",
  "parroquia CCC",
  "CCC cerca de mí",
  "Iglesia Celestial cerca de mí",
  "mapa de parroquias CCC",
  "Celestial Church en vivo",
  "CCC en vivo",
  "TV Celestial Church",
  "transmisión Celestial Church",
  "documentos CCC",
  "constitución Celestial Church",
  "doctrina CCC",
];

export const SEO_KEYWORDS_CONTENT = SEO_KEYWORDS.join(", ");

export const SEO_TOPIC_THINGS = [
  "Cele One",
  "Cèlè One",
  "CeleOne",
  "Celeone TV",
  "Celestial Church of Christ",
  "CCC Worldwide",
  "Celestial Church community platform",
  "Celestial Church social media",
  "Celestial Church news",
  "Celestial Church hymns",
  "CCC hymn book",
  "Celestial Church weekly theme",
  "Celestial Church Bible readings",
  "Celestial Church spiritual program",
  "Celestial Church worship program",
  "Celestial Church parish map",
  "Celestial Church live TV",
  "Celestial Church radio",
  "Celestial Church documents",
  "Celestial Church doctrine",
  "Celestial Church order of service",
  "Celestial Church harvest",
  "Samuel Bilehou Joseph Oshoffa",
  "SBJ Oshoffa",
  "founder of Celestial Church of Christ",
  "Église du Christianisme Céleste",
  "communauté céleste",
  "réseau social ECC",
  "actualités ECC",
  "cantiques célestes",
  "thème de la semaine ECC",
  "programme spirituel ECC",
  "lectures bibliques ECC",
  "culte dominical ECC",
  "carte des paroisses ECC",
  "Église Céleste en direct",
  "documents officiels ECC",
  "constitution ECC",
  "doctrine ECC",
  "moisson ECC",
  "Papa Oshoffa",
  "fondateur Église du Christianisme Céleste",
  "Ijo Mimo ti Kristi lati Orun Wa",
  "Celestial Church Yoruba",
  "CCC Yoruba",
  "CCC Yoruba hymns",
  "CCC Yoruba weekly theme",
  "CCC Yoruba spiritual program",
  "CCC Nigeria parishes",
  "CCC Fon",
  "ECC Fon",
  "Cèlè One Fon",
  "cantiques célestes Fon",
  "thème de la semaine Fon",
  "CCC Goun",
  "CCC Gungbe",
  "Cele One Goun",
  "Cele One Gungbe",
  "programme spirituel Gungbe",
  "Celestial Church of Christ en español",
  "Iglesia del Cristianismo Celestial",
  "Cele One español",
  "himnos CCC",
  "tema de la semana CCC",
  "programa espiritual CCC",
  "mapa de parroquias CCC",
  "CCC en vivo",
  "documentos CCC",
  "doctrina CCC",
];
